export const USER_DATA = {
  GET_USER_DATA: "GET_USER_DATA",
  GET_USER_DATA_START: "GET_USER_DATA_START",
  GET_USER_DATA_SUCCESS: "GET_USER_DATA_SUCCESS",
  GET_USER_DATA_FAIL: "GET_USER_DATA_FAIL",
  USER_NOT_EXIST: "USER_NOT_EXIST",
  WRONG_PASSWORD: "WRONG_PASSWORD",
  EXIT_USER: "EXIT_USER",
} as const;
